name: Windows
on: [push, pull_request, workflow_dispatch]
jobs:
  WindowsRun:
    runs-on: windows-2019
    steps:            
      - name: Checkout
        uses: actions/checkout@v2            
      - name: Create build directory
        run: mkdir ${{github.workspace}}/build      
      - name: Configure CMake
        working-directory: ${{github.workspace}}/build
        run: cmake ../
      - name: Run VS
        run: cmake --build ${{github.workspace}}/build --clean-first --config Release -j 4
      - name: Run Test
        working-directory: ${{github.workspace}}/build
        run: bin\Release\VS_OMP.exe
      - run: echo "This job's status is ${{ job.status }}."
